version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 8888:8888
    env_file:
      - .env.prod
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - kimo_ai:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=kimo_ai
    ports:
      - 27017:27017

volumes:
  kimo_ai: